# Generated by Django 4.1.7 on 2023-03-16 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_model_name', models.CharField(choices=[('Demo Model 1', 'Demo Model 1'), ('Demo Model 2', 'Demo Model 2'), ('Demo Model 3', 'Demo Model 3'), ('Demo Model 4', 'Demo Model 4'), ('Demo Model 5', 'Demo Model 5'), ('Demo Model Default', 'Demo Model Default')], default='Demo Model Default', max_length=50)),
                ('manufacturing_date', models.DateTimeField()),
                ('manufacturer_info', models.CharField(choices=[('Manufacturer Model 1', 'Mn Model 1'), ('Manufacturer Model 2', 'Mn Model 2'), ('Manufacturer Model 3', 'Mn Model 3'), ('Manufacturer Model 4', 'Mn Model 4'), ('Manufacturer Model 5', 'Mn Model 5'), ('Manufacturer Model Default', 'Mn Model Default')], default='Manufacturer Model Default', max_length=50)),
                ('color', models.CharField(choices=[('Color 1', 'Color 1'), ('Color 2', 'Color 2'), ('Color Default', 'Color Default')], default='Color Default', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
